### ISSUE TITLE
Trained model fails at lower graphic quality

### ISSUE THREAD

**Issue by w4zir** [upul/behavioral_cloning#3]
I was testing your trained model. When i ran it on udacity simulator with high graphic quality (fantastic in simulator) the model ran perfectly and the car was driving on the road successfully as shown in this [video](https://youtu.be/koTrixVW_Y8). But when I changed graphic quality to medium (Good in simulator), the car failed as shown in this [video](https://youtu.be/3C7NFYBEwdA). Any idea why this is happening ?

**Comment by upul** [comment]
Checked both videos. For me, it looks like you simulator is not smoothly running. Probably, resources (CPU and Memory) might not enough to run the simulator with high/medium quality graphics. Can you please start it with the following configurations?

1. Screen Resolution: 640x480 
2. Graphics Quality: Fastest

Thanks,
Upul

**Comment by w4zir** [comment]
On 640x480, it runs successfully at fast and fastest but fails at other. It could be an issue with my graphics processor. I am currently running it on CPU. What configurations you used for training data ?

**Comment by upul** [comment]
Yes, it looks resources (CPU and memory) are enough to run it with high-quality graphics.  

> I'm using a laptop (T540p Lenovo) with 16GB RAM.

**Comment by upul** [comment]
Answered hence, closing this issue

**Comment by upul** [comment]
Answered hence, closing this issue
